"""baseline: reflect current live schema

This migration does NOT build the schema from models.py — it was generated by
reflecting the actual live database (SQLAlchemy MetaData.reflect() + pg_catalog
introspection for views/functions/triggers), because models.py has real,
previously-undocumented drift from production: a legacy 'sessions' table with
no ORM model (superseded by user_sessions, unreferenced by any code), columns
like customers.created_by / user_customers.assigned_by / user_roles.assigned_by
that exist live but aren't in any model, and several type/nullability
mismatches (see the architecture assessment, "Phase 5" discussion). Building
the baseline from models.py would have produced a migration that silently
diverges from what's actually running — dropping the sessions table, missing
real columns — which is worse than not having Alembic at all.

INTENDED USE: run `alembic stamp head` against a database that is ALREADY at
this schema (i.e. any currently-deployed CygnetCI database) — stamp never
executes upgrade()/downgrade(), it only records the revision, so this is safe
regardless of any imperfection in the DDL below. This revision's upgrade() has
NOT been verified against a truly empty database (no spare Postgres instance
was available to test against, and the live database was intentionally left
untouched beyond this file). Treat "run upgrade() to bootstrap a fresh
install" as unverified until someone confirms it end-to-end against a
throwaway database.

From this revision forward, all schema changes should go through
`alembic revision --autogenerate` + review + `alembic upgrade head` — not the
ad hoc run_*.py / add_*.py / fix_*.py scripts at the CygnetCI.Api root, which
are now historical (kept for reference, not for new changes).

Revision ID: e56a0c445b8a
Revises: 
Create Date: 2026-09-10 02:39:50.159785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56a0c445b8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_BASELINE_DDL = """
-- ============================================================
-- Tables (dependency order)
-- ============================================================
CREATE TABLE alert_settings (
	id SERIAL NOT NULL, 
	key VARCHAR(100) NOT NULL, 
	value VARCHAR(255) NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	CONSTRAINT alert_settings_pkey PRIMARY KEY (id), 
	CONSTRAINT alert_settings_key_key UNIQUE (key)
);

CREATE TABLE app_settings (
	id SERIAL NOT NULL, 
	key VARCHAR(100) NOT NULL, 
	value TEXT, 
	description TEXT, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	CONSTRAINT app_settings_pkey PRIMARY KEY (id), 
	CONSTRAINT app_settings_key_key UNIQUE (key)
);

CREATE TABLE email_log (
	id SERIAL NOT NULL, 
	recipient TEXT NOT NULL, 
	email_type VARCHAR(50), 
	template VARCHAR(100), 
	subject VARCHAR(500), 
	provider VARCHAR(50), 
	status VARCHAR(20) DEFAULT 'pending'::character varying NOT NULL, 
	error TEXT, 
	message_id VARCHAR(255), 
	idempotency_key VARCHAR(255), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	sent_at TIMESTAMP WITHOUT TIME ZONE, 
	CONSTRAINT email_log_pkey PRIMARY KEY (id)
);

CREATE TABLE email_templates (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	subject VARCHAR(500) NOT NULL, 
	html_body TEXT NOT NULL, 
	text_body TEXT, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	CONSTRAINT email_templates_pkey PRIMARY KEY (id), 
	CONSTRAINT email_templates_name_key UNIQUE (name)
);

CREATE TABLE environments (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	description TEXT, 
	order_index INTEGER DEFAULT 0, 
	requires_approval BOOLEAN DEFAULT false, 
	approvers TEXT[], 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT environments_pkey PRIMARY KEY (id), 
	CONSTRAINT environments_name_key UNIQUE (name)
);

CREATE TABLE roles (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	description TEXT, 
	permissions JSONB, 
	is_system BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE rollback_scripts (
	id SERIAL NOT NULL, 
	filename VARCHAR(500) NOT NULL, 
	file_path VARCHAR(1000) NOT NULL, 
	description TEXT, 
	uploaded_by VARCHAR(255), 
	uploaded_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	file_size BIGINT, 
	analysis_status VARCHAR(50) NOT NULL, 
	analysis_started_at TIMESTAMP WITHOUT TIME ZONE, 
	analysis_completed_at TIMESTAMP WITHOUT TIME ZONE, 
	error_message TEXT, 
	CONSTRAINT rollback_scripts_pkey PRIMARY KEY (id)
);

CREATE TABLE statistics (
	id SERIAL NOT NULL, 
	stat_date DATE NOT NULL, 
	active_agents INTEGER DEFAULT 0, 
	running_pipelines INTEGER DEFAULT 0, 
	success_rate NUMERIC(5, 2) DEFAULT 0.00, 
	avg_deploy_time VARCHAR(50), 
	total_deployments INTEGER DEFAULT 0, 
	successful_deployments INTEGER DEFAULT 0, 
	failed_deployments INTEGER DEFAULT 0, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT statistics_pkey PRIMARY KEY (id), 
	CONSTRAINT statistics_stat_date_key UNIQUE (stat_date), 
	CONSTRAINT check_success_rate CHECK (success_rate >= 0::numeric AND success_rate <= 100::numeric)
);

CREATE TABLE system_modules (
	id SERIAL NOT NULL, 
	key VARCHAR(50) NOT NULL, 
	display_name VARCHAR(100) NOT NULL, 
	enabled BOOLEAN NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT system_modules_pkey PRIMARY KEY (id)
);

CREATE TABLE transfer_files (
	id SERIAL NOT NULL, 
	file_type VARCHAR(50) NOT NULL, 
	file_name VARCHAR(255) NOT NULL, 
	version VARCHAR(100) NOT NULL, 
	file_path TEXT NOT NULL, 
	file_size_bytes BIGINT, 
	checksum VARCHAR(255), 
	uploaded_by VARCHAR(255), 
	description TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT transfer_files_pkey PRIMARY KEY (id), 
	CONSTRAINT transfer_files_file_type_file_name_version_key UNIQUE (file_type, file_name, version), 
	CONSTRAINT transfer_files_file_type_check CHECK (file_type::text = ANY (ARRAY['script'::character varying::text, 'artifact'::character varying::text]))
);

CREATE TABLE users (
	id SERIAL NOT NULL, 
	username VARCHAR(100) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	full_name VARCHAR(255), 
	is_active BOOLEAN NOT NULL, 
	is_superuser BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	last_login TIMESTAMP WITHOUT TIME ZONE, 
	created_by INTEGER, 
	CONSTRAINT users_pkey PRIMARY KEY (id), 
	CONSTRAINT users_created_by_fkey FOREIGN KEY(created_by) REFERENCES users (id)
);

CREATE TABLE variable_groups (
	id SERIAL NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	created_by VARCHAR(255), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT variable_groups_pkey PRIMARY KEY (id), 
	CONSTRAINT variable_groups_name_key UNIQUE (name)
);

CREATE TABLE audit_logs (
	id SERIAL NOT NULL, 
	user_id INTEGER, 
	action VARCHAR(100) NOT NULL, 
	resource_type VARCHAR(100) NOT NULL, 
	resource_id VARCHAR(100), 
	details JSONB, 
	ip_address VARCHAR(50), 
	user_agent VARCHAR(500), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	created_by INTEGER, 
	CONSTRAINT audit_logs_pkey PRIMARY KEY (id), 
	CONSTRAINT audit_logs_created_by_fkey FOREIGN KEY(created_by) REFERENCES users (id), 
	CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE customers (
	id SERIAL NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	display_name VARCHAR(255) NOT NULL, 
	description TEXT, 
	contact_email VARCHAR(255), 
	contact_phone VARCHAR(50), 
	address TEXT, 
	is_active BOOLEAN NOT NULL, 
	logo_url VARCHAR(500), 
	settings JSONB, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	created_by INTEGER, 
	client_id VARCHAR(64), 
	client_secret VARCHAR(128), 
	credentials_enabled BOOLEAN DEFAULT false NOT NULL, 
	ip_allowlist JSONB, 
	ip_restriction_enabled BOOLEAN DEFAULT false NOT NULL, 
	CONSTRAINT customers_pkey PRIMARY KEY (id), 
	CONSTRAINT customers_created_by_fkey FOREIGN KEY(created_by) REFERENCES users (id), 
	CONSTRAINT customers_client_id_key UNIQUE (client_id)
);

CREATE TABLE password_reset_tokens (
	id SERIAL NOT NULL, 
	user_id INTEGER NOT NULL, 
	token_hash VARCHAR(64) NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	used_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id), 
	CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT password_reset_tokens_token_hash_key UNIQUE (token_hash)
);

CREATE TABLE rollback_database_objects (
	id SERIAL NOT NULL, 
	script_id INTEGER NOT NULL, 
	database_name VARCHAR(255), 
	object_type VARCHAR(50) NOT NULL, 
	object_name VARCHAR(500) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT rollback_database_objects_pkey PRIMARY KEY (id), 
	CONSTRAINT rollback_database_objects_script_id_fkey FOREIGN KEY(script_id) REFERENCES rollback_scripts (id) ON DELETE CASCADE
);

CREATE TABLE sessions (
	id SERIAL NOT NULL, 
	session_token VARCHAR(255) NOT NULL, 
	user_id INTEGER NOT NULL, 
	ip_address VARCHAR(50), 
	user_agent VARCHAR(500), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	last_activity TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	CONSTRAINT sessions_pkey PRIMARY KEY (id), 
	CONSTRAINT sessions_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE transfer_file_pickup (
	id SERIAL NOT NULL, 
	transfer_file_id INTEGER NOT NULL, 
	agent_uuid VARCHAR(255) NOT NULL, 
	agent_name VARCHAR(255), 
	file_type VARCHAR(50) NOT NULL, 
	version VARCHAR(100) NOT NULL, 
	status VARCHAR(50) DEFAULT 'pending'::character varying, 
	requested_by VARCHAR(255), 
	requested_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	downloaded_at TIMESTAMP WITHOUT TIME ZONE, 
	acknowledged_at TIMESTAMP WITHOUT TIME ZONE, 
	error_message TEXT, 
	CONSTRAINT transfer_file_pickup_pkey PRIMARY KEY (id), 
	CONSTRAINT transfer_file_pickup_transfer_file_id_fkey FOREIGN KEY(transfer_file_id) REFERENCES transfer_files (id) ON DELETE CASCADE, 
	CONSTRAINT transfer_file_pickup_file_type_check CHECK (file_type::text = ANY (ARRAY['script'::character varying::text, 'artifact'::character varying::text])), 
	CONSTRAINT transfer_file_pickup_status_check CHECK (status::text = ANY (ARRAY['pending'::character varying, 'downloading'::character varying, 'downloaded'::character varying, 'failed'::character varying]::text[]))
);

CREATE TABLE user_roles (
	id SERIAL NOT NULL, 
	user_id INTEGER NOT NULL, 
	role_id INTEGER NOT NULL, 
	assigned_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	assigned_by INTEGER, 
	CONSTRAINT user_roles_pkey PRIMARY KEY (id), 
	CONSTRAINT user_roles_assigned_by_fkey FOREIGN KEY(assigned_by) REFERENCES users (id), 
	CONSTRAINT user_roles_role_id_fkey FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE, 
	CONSTRAINT user_roles_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_sessions (
	id SERIAL NOT NULL, 
	token_hash VARCHAR(64) NOT NULL, 
	user_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	last_used_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	CONSTRAINT user_sessions_pkey PRIMARY KEY (id), 
	CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	CONSTRAINT user_sessions_token_hash_key UNIQUE (token_hash)
);

CREATE TABLE variables (
	id SERIAL NOT NULL, 
	variable_group_id INTEGER, 
	environment_id INTEGER, 
	key VARCHAR(255) NOT NULL, 
	value TEXT, 
	is_secret BOOLEAN DEFAULT false, 
	description TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT variables_pkey PRIMARY KEY (id), 
	CONSTRAINT variables_environment_id_fkey FOREIGN KEY(environment_id) REFERENCES environments (id) ON DELETE CASCADE, 
	CONSTRAINT variables_variable_group_id_fkey FOREIGN KEY(variable_group_id) REFERENCES variable_groups (id) ON DELETE CASCADE
);

CREATE TABLE agents (
	id SERIAL NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	uuid VARCHAR(255) NOT NULL, 
	description TEXT, 
	location VARCHAR(255) NOT NULL, 
	status VARCHAR(50) DEFAULT 'offline'::character varying NOT NULL, 
	last_seen TIMESTAMP WITHOUT TIME ZONE, 
	jobs INTEGER DEFAULT 0, 
	cpu INTEGER DEFAULT 0, 
	memory INTEGER DEFAULT 0, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	customer_id INTEGER NOT NULL, 
	parent_agent_id INTEGER, 
	CONSTRAINT agents_pkey PRIMARY KEY (id), 
	CONSTRAINT agents_customer_id_fkey FOREIGN KEY(customer_id) REFERENCES customers (id) ON DELETE CASCADE, 
	CONSTRAINT fk_agents_parent_agent FOREIGN KEY(parent_agent_id) REFERENCES agents (id) ON DELETE SET NULL, 
	CONSTRAINT agents_uuid_key UNIQUE (uuid), 
	CONSTRAINT check_cpu CHECK (cpu >= 0 AND cpu <= 100), 
	CONSTRAINT check_memory CHECK (memory >= 0 AND memory <= 100), 
	CONSTRAINT check_status CHECK (status::text = ANY (ARRAY['online'::character varying::text, 'offline'::character varying::text, 'busy'::character varying::text]))
);

CREATE TABLE ai_settings (
	id SERIAL NOT NULL, 
	provider VARCHAR(50) NOT NULL, 
	model VARCHAR(100) NOT NULL, 
	api_key_encrypted TEXT, 
	customer_id INTEGER, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	CONSTRAINT ai_settings_pkey PRIMARY KEY (id), 
	CONSTRAINT ai_settings_customer_id_fkey FOREIGN KEY(customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

CREATE TABLE email_alerts (
	id SERIAL NOT NULL, 
	subject VARCHAR(500) NOT NULL, 
	sender VARCHAR(255) NOT NULL, 
	sender_email VARCHAR(255) NOT NULL, 
	preview VARCHAR(500), 
	body TEXT, 
	received_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	category VARCHAR(50) NOT NULL, 
	is_read BOOLEAN NOT NULL, 
	is_starred BOOLEAN NOT NULL, 
	has_attachment BOOLEAN NOT NULL, 
	priority VARCHAR(20) NOT NULL, 
	customer_id INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT email_alerts_pkey PRIMARY KEY (id), 
	CONSTRAINT email_alerts_customer_id_fkey FOREIGN KEY(customer_id) REFERENCES customers (id) ON DELETE CASCADE, 
	CONSTRAINT check_email_category CHECK (category::text = ANY (ARRAY['inbox'::character varying::text, 'ignorable'::character varying::text, 'moderate'::character varying::text, 'critical'::character varying::text, 'resolved'::character varying::text])), 
	CONSTRAINT check_email_priority CHECK (priority::text = ANY (ARRAY['low'::character varying::text, 'medium'::character varying::text, 'high'::character varying::text]))
);

CREATE TABLE email_configs (
	id SERIAL NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	email_address VARCHAR(255) NOT NULL, 
	server_type VARCHAR(20) NOT NULL, 
	server_host VARCHAR(255) NOT NULL, 
	server_port INTEGER NOT NULL, 
	username VARCHAR(255) NOT NULL, 
	password_encrypted TEXT NOT NULL, 
	use_ssl BOOLEAN NOT NULL, 
	folder VARCHAR(255), 
	is_active BOOLEAN NOT NULL, 
	last_sync_at TIMESTAMP WITHOUT TIME ZONE, 
	last_sync_status VARCHAR(50), 
	last_sync_message TEXT, 
	customer_id INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT email_configs_pkey PRIMARY KEY (id), 
	CONSTRAINT email_configs_customer_id_fkey FOREIGN KEY(customer_id) REFERENCES customers (id) ON DELETE CASCADE, 
	CONSTRAINT check_server_type CHECK (server_type::text = ANY (ARRAY['imap'::character varying::text, 'pop3'::character varying::text]))
);

CREATE TABLE services (
	id VARCHAR(255) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	type VARCHAR(50) NOT NULL, 
	url TEXT NOT NULL, 
	status VARCHAR(50) DEFAULT 'unknown'::character varying NOT NULL, 
	category VARCHAR(50) DEFAULT 'todo'::character varying NOT NULL, 
	last_check TIMESTAMP WITHOUT TIME ZONE, 
	response_time VARCHAR(50), 
	uptime NUMERIC(5, 2), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	customer_id INTEGER NOT NULL, 
	CONSTRAINT services_pkey PRIMARY KEY (id), 
	CONSTRAINT services_customer_id_fkey FOREIGN KEY(customer_id) REFERENCES customers (id) ON DELETE CASCADE, 
	CONSTRAINT check_service_category CHECK (category::text = ANY (ARRAY['todo'::character varying::text, 'monitoring'::character varying::text, 'issues'::character varying::text, 'healthy'::character varying::text])), 
	CONSTRAINT check_service_status CHECK (status::text = ANY (ARRAY['healthy'::character varying::text, 'warning'::character varying::text, 'critical'::character varying::text, 'down'::character varying::text, 'unknown'::character varying::text])), 
	CONSTRAINT check_service_type CHECK (type::text = ANY (ARRAY['website'::character varying::text, 'database'::character varying::text, 'api'::character varying::text, 'service'::character varying::text]))
);

CREATE TABLE user_customers (
	id SERIAL NOT NULL, 
	user_id INTEGER NOT NULL, 
	customer_id INTEGER NOT NULL, 
	is_default BOOLEAN, 
	assigned_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	assigned_by INTEGER, 
	CONSTRAINT user_customers_pkey PRIMARY KEY (id), 
	CONSTRAINT user_customers_assigned_by_fkey FOREIGN KEY(assigned_by) REFERENCES users (id), 
	CONSTRAINT user_customers_customer_id_fkey FOREIGN KEY(customer_id) REFERENCES customers (id) ON DELETE CASCADE, 
	CONSTRAINT user_customers_user_id_fkey FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE agent_commands (
	id SERIAL NOT NULL, 
	agent_id INTEGER NOT NULL, 
	command_type VARCHAR(50) NOT NULL, 
	command_data TEXT NOT NULL, 
	status VARCHAR(50) NOT NULL, 
	result TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	CONSTRAINT agent_commands_pkey PRIMARY KEY (id), 
	CONSTRAINT agent_commands_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
	CONSTRAINT check_command_status CHECK (status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])), 
	CONSTRAINT check_command_type CHECK (command_type::text = ANY (ARRAY['service_control'::character varying, 'execute_script'::character varying, 'system_command'::character varying, 'service_log_list'::character varying, 'service_log_read'::character varying, 'k8s_onboard'::character varying, 'k8s_argocd_sync'::character varying]::text[]))
);

CREATE TABLE agent_drive_info (
	id SERIAL NOT NULL, 
	agent_id INTEGER NOT NULL, 
	drive_letter VARCHAR(10) NOT NULL, 
	drive_label VARCHAR(255), 
	total_gb BIGINT NOT NULL, 
	used_gb BIGINT NOT NULL, 
	free_gb BIGINT NOT NULL, 
	percent_used INTEGER NOT NULL, 
	reported_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT agent_drive_info_pkey PRIMARY KEY (id), 
	CONSTRAINT agent_drive_info_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
	CONSTRAINT check_percent_used CHECK (percent_used >= 0 AND percent_used <= 100)
);

CREATE TABLE agent_logs (
	id SERIAL NOT NULL, 
	agent_id INTEGER NOT NULL, 
	timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	level VARCHAR(50) NOT NULL, 
	message TEXT NOT NULL, 
	details TEXT, 
	CONSTRAINT agent_logs_pkey PRIMARY KEY (id), 
	CONSTRAINT agent_logs_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
	CONSTRAINT check_log_level CHECK (level::text = ANY (ARRAY['info'::character varying::text, 'success'::character varying::text, 'warning'::character varying::text, 'error'::character varying::text]))
);

CREATE TABLE agent_resource_data (
	id SERIAL NOT NULL, 
	agent_id INTEGER NOT NULL, 
	timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	cpu INTEGER NOT NULL, 
	memory INTEGER NOT NULL, 
	disk INTEGER NOT NULL, 
	CONSTRAINT agent_resource_data_pkey PRIMARY KEY (id), 
	CONSTRAINT agent_resource_data_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
	CONSTRAINT check_cpu CHECK (cpu >= 0 AND cpu <= 100), 
	CONSTRAINT check_disk CHECK (disk >= 0 AND disk <= 100), 
	CONSTRAINT check_memory CHECK (memory >= 0 AND memory <= 100)
);

CREATE TABLE agent_website_pings (
	id SERIAL NOT NULL, 
	agent_id INTEGER NOT NULL, 
	url VARCHAR(500) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	status VARCHAR(50) NOT NULL, 
	response_time_ms INTEGER NOT NULL, 
	checked_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT agent_website_pings_pkey PRIMARY KEY (id), 
	CONSTRAINT agent_website_pings_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
	CONSTRAINT check_ping_status CHECK (status::text = ANY (ARRAY['healthy'::character varying::text, 'unhealthy'::character varying::text, 'timeout'::character varying::text]))
);

CREATE TABLE agent_windows_services (
	id SERIAL NOT NULL, 
	agent_id INTEGER NOT NULL, 
	service_name VARCHAR(255) NOT NULL, 
	display_name VARCHAR(255) NOT NULL, 
	status VARCHAR(50) NOT NULL, 
	description TEXT, 
	reported_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT agent_windows_services_pkey PRIMARY KEY (id), 
	CONSTRAINT agent_windows_services_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
	CONSTRAINT check_service_status CHECK (status::text = ANY (ARRAY['Running'::character varying::text, 'Stopped'::character varying::text, 'Paused'::character varying::text, 'StartPending'::character varying::text, 'StopPending'::character varying::text, 'ContinuePending'::character varying::text, 'PausePending'::character varying::text]))
);

CREATE TABLE pipelines (
	id SERIAL NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	status VARCHAR(50) DEFAULT 'pending'::character varying NOT NULL, 
	branch VARCHAR(255) NOT NULL, 
	commit VARCHAR(255), 
	last_run TIMESTAMP WITHOUT TIME ZONE, 
	duration VARCHAR(50), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	agent_id INTEGER, 
	customer_id INTEGER NOT NULL, 
	log_verbose_output BOOLEAN DEFAULT false NOT NULL, 
	CONSTRAINT pipelines_pkey PRIMARY KEY (id), 
	CONSTRAINT pipelines_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE SET NULL, 
	CONSTRAINT pipelines_customer_id_fkey FOREIGN KEY(customer_id) REFERENCES customers (id) ON DELETE CASCADE, 
	CONSTRAINT check_pipeline_status CHECK (status::text = ANY (ARRAY['success'::character varying::text, 'failed'::character varying::text, 'running'::character varying::text, 'pending'::character varying::text]))
);

CREATE TABLE service_health_history (
	id SERIAL NOT NULL, 
	service_id VARCHAR(255) NOT NULL, 
	timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	status VARCHAR(50) NOT NULL, 
	response_time VARCHAR(50), 
	CONSTRAINT service_health_history_pkey PRIMARY KEY (id), 
	CONSTRAINT service_health_history_service_id_fkey FOREIGN KEY(service_id) REFERENCES services (id) ON DELETE CASCADE, 
	CONSTRAINT check_health_status CHECK (status::text = ANY (ARRAY['healthy'::character varying::text, 'warning'::character varying::text, 'critical'::character varying::text, 'down'::character varying::text, 'unknown'::character varying::text]))
);

CREATE TABLE pipeline_parameters (
	id SERIAL NOT NULL, 
	pipeline_id INTEGER NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	type VARCHAR(50) NOT NULL, 
	default_value TEXT, 
	required BOOLEAN DEFAULT false, 
	description TEXT, 
	choices JSONB, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT pipeline_parameters_pkey PRIMARY KEY (id), 
	CONSTRAINT pipeline_parameters_pipeline_id_fkey FOREIGN KEY(pipeline_id) REFERENCES pipelines (id) ON DELETE CASCADE, 
	CONSTRAINT unique_pipeline_param_name UNIQUE (pipeline_id, name), 
	CONSTRAINT check_param_type CHECK (type::text = ANY (ARRAY['string'::character varying::text, 'number'::character varying::text, 'boolean'::character varying::text, 'choice'::character varying::text]))
);

CREATE TABLE pipeline_steps (
	id SERIAL NOT NULL, 
	pipeline_id INTEGER NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	command TEXT NOT NULL, 
	step_order INTEGER NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	shell_type VARCHAR(20) DEFAULT 'cmd'::character varying, 
	CONSTRAINT pipeline_steps_pkey PRIMARY KEY (id), 
	CONSTRAINT pipeline_steps_pipeline_id_fkey FOREIGN KEY(pipeline_id) REFERENCES pipelines (id) ON DELETE CASCADE, 
	CONSTRAINT unique_pipeline_step_order UNIQUE (pipeline_id, step_order), 
	CONSTRAINT check_shell_type CHECK (shell_type::text = ANY (ARRAY['powershell'::character varying::text, 'cmd'::character varying::text, 'bash'::character varying::text]))
);

CREATE TABLE releases (
	id SERIAL NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	pipeline_id INTEGER, 
	version VARCHAR(100), 
	status VARCHAR(50) DEFAULT 'active'::character varying, 
	created_by VARCHAR(255), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	customer_id INTEGER NOT NULL, 
	CONSTRAINT releases_pkey PRIMARY KEY (id), 
	CONSTRAINT releases_customer_id_fkey FOREIGN KEY(customer_id) REFERENCES customers (id) ON DELETE CASCADE, 
	CONSTRAINT releases_pipeline_id_fkey FOREIGN KEY(pipeline_id) REFERENCES pipelines (id) ON DELETE SET NULL, 
	CONSTRAINT check_release_status CHECK (status::text = ANY (ARRAY['active'::character varying::text, 'disabled'::character varying::text, 'archived'::character varying::text]))
);

CREATE TABLE tasks (
	id SERIAL NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	pipeline_id INTEGER, 
	agent_id INTEGER, 
	pipeline_name VARCHAR(255), 
	agent_name VARCHAR(255), 
	status VARCHAR(50) DEFAULT 'queued'::character varying NOT NULL, 
	start_time TIMESTAMP WITHOUT TIME ZONE, 
	end_time TIMESTAMP WITHOUT TIME ZONE, 
	duration VARCHAR(50), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT tasks_pkey PRIMARY KEY (id), 
	CONSTRAINT tasks_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE SET NULL, 
	CONSTRAINT tasks_pipeline_id_fkey FOREIGN KEY(pipeline_id) REFERENCES pipelines (id) ON DELETE SET NULL, 
	CONSTRAINT check_task_status CHECK (status::text = ANY (ARRAY['completed'::character varying::text, 'running'::character varying::text, 'queued'::character varying::text, 'failed'::character varying::text]))
);

CREATE TABLE release_executions (
	id SERIAL NOT NULL, 
	release_id INTEGER, 
	release_number VARCHAR(50) NOT NULL, 
	triggered_by VARCHAR(255), 
	status VARCHAR(50) DEFAULT 'pending'::character varying, 
	artifact_version VARCHAR(100), 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	duration_seconds INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT release_executions_pkey PRIMARY KEY (id), 
	CONSTRAINT release_executions_release_id_fkey FOREIGN KEY(release_id) REFERENCES releases (id) ON DELETE CASCADE, 
	CONSTRAINT check_release_execution_status CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'in_progress'::character varying::text, 'succeeded'::character varying::text, 'failed'::character varying::text, 'cancelled'::character varying::text, 'partially_succeeded'::character varying::text]))
);

CREATE TABLE release_pipelines (
	id SERIAL NOT NULL, 
	release_id INTEGER NOT NULL, 
	pipeline_id INTEGER NOT NULL, 
	order_index INTEGER NOT NULL, 
	execution_mode VARCHAR(50), 
	depends_on INTEGER, 
	position_x INTEGER, 
	position_y INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	CONSTRAINT release_pipelines_pkey PRIMARY KEY (id), 
	CONSTRAINT release_pipelines_depends_on_fkey FOREIGN KEY(depends_on) REFERENCES release_pipelines (id) ON DELETE SET NULL, 
	CONSTRAINT release_pipelines_pipeline_id_fkey FOREIGN KEY(pipeline_id) REFERENCES pipelines (id) ON DELETE CASCADE, 
	CONSTRAINT release_pipelines_release_id_fkey FOREIGN KEY(release_id) REFERENCES releases (id) ON DELETE CASCADE, 
	CONSTRAINT check_execution_mode CHECK (execution_mode::text = ANY (ARRAY['sequential'::character varying::text, 'parallel'::character varying::text]))
);

CREATE TABLE release_stages (
	id SERIAL NOT NULL, 
	release_id INTEGER, 
	environment_id INTEGER, 
	order_index INTEGER NOT NULL, 
	pipeline_id INTEGER, 
	pre_deployment_approval BOOLEAN DEFAULT false, 
	post_deployment_approval BOOLEAN DEFAULT false, 
	auto_deploy BOOLEAN DEFAULT false, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	agent_id INTEGER, 
	CONSTRAINT release_stages_pkey PRIMARY KEY (id), 
	CONSTRAINT release_stages_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE SET NULL, 
	CONSTRAINT release_stages_environment_id_fkey FOREIGN KEY(environment_id) REFERENCES environments (id) ON DELETE CASCADE, 
	CONSTRAINT release_stages_pipeline_id_fkey FOREIGN KEY(pipeline_id) REFERENCES pipelines (id) ON DELETE SET NULL, 
	CONSTRAINT release_stages_release_id_fkey FOREIGN KEY(release_id) REFERENCES releases (id) ON DELETE CASCADE, 
	CONSTRAINT release_stages_release_id_environment_id_key UNIQUE (release_id, environment_id)
);

CREATE TABLE tickets (
	id SERIAL NOT NULL, 
	ticket_number VARCHAR(20) NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	description TEXT, 
	status VARCHAR(20) NOT NULL, 
	priority VARCHAR(20) NOT NULL, 
	type VARCHAR(20) NOT NULL, 
	created_by INTEGER, 
	assigned_to INTEGER, 
	customer_id INTEGER, 
	pipeline_id INTEGER, 
	release_id INTEGER, 
	agent_id INTEGER, 
	root_cause TEXT, 
	resolution_steps JSONB, 
	resolution_commands TEXT, 
	resolved_by INTEGER, 
	resolved_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT tickets_pkey PRIMARY KEY (id), 
	CONSTRAINT tickets_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE SET NULL, 
	CONSTRAINT tickets_assigned_to_fkey FOREIGN KEY(assigned_to) REFERENCES users (id) ON DELETE SET NULL, 
	CONSTRAINT tickets_created_by_fkey FOREIGN KEY(created_by) REFERENCES users (id) ON DELETE SET NULL, 
	CONSTRAINT tickets_customer_id_fkey FOREIGN KEY(customer_id) REFERENCES customers (id) ON DELETE SET NULL, 
	CONSTRAINT tickets_pipeline_id_fkey FOREIGN KEY(pipeline_id) REFERENCES pipelines (id) ON DELETE SET NULL, 
	CONSTRAINT tickets_release_id_fkey FOREIGN KEY(release_id) REFERENCES releases (id) ON DELETE SET NULL, 
	CONSTRAINT tickets_resolved_by_fkey FOREIGN KEY(resolved_by) REFERENCES users (id) ON DELETE SET NULL, 
	CONSTRAINT check_ticket_priority CHECK (priority::text = ANY (ARRAY['critical'::character varying, 'high'::character varying, 'medium'::character varying, 'low'::character varying]::text[])), 
	CONSTRAINT check_ticket_status CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])), 
	CONSTRAINT check_ticket_type CHECK (type::text = ANY (ARRAY['bug'::character varying, 'task'::character varying, 'improvement'::character varying, 'question'::character varying]::text[]))
);

CREATE TABLE pipeline_executions (
	id SERIAL NOT NULL, 
	pipeline_id INTEGER NOT NULL, 
	status VARCHAR(50) NOT NULL, 
	started_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	duration VARCHAR(50), 
	commit VARCHAR(255), 
	triggered_by VARCHAR(255), 
	agent_id INTEGER, 
	agent_name VARCHAR(255), 
	release_execution_id INTEGER, 
	release_pipeline_id INTEGER, 
	CONSTRAINT pipeline_executions_pkey PRIMARY KEY (id), 
	CONSTRAINT pipeline_executions_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE SET NULL, 
	CONSTRAINT pipeline_executions_pipeline_id_fkey FOREIGN KEY(pipeline_id) REFERENCES pipelines (id) ON DELETE CASCADE, 
	CONSTRAINT pipeline_executions_release_execution_id_fkey FOREIGN KEY(release_execution_id) REFERENCES release_executions (id) ON DELETE SET NULL, 
	CONSTRAINT pipeline_executions_release_pipeline_id_fkey FOREIGN KEY(release_pipeline_id) REFERENCES release_pipelines (id) ON DELETE SET NULL, 
	CONSTRAINT check_execution_status CHECK (status::text = ANY (ARRAY['success'::character varying::text, 'failed'::character varying::text, 'running'::character varying::text, 'cancelled'::character varying::text, 'pending'::character varying::text]))
);

CREATE TABLE release_execution_parameters (
	id SERIAL NOT NULL, 
	release_execution_id INTEGER, 
	parameter_name VARCHAR(255) NOT NULL, 
	parameter_value TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT release_execution_parameters_pkey PRIMARY KEY (id), 
	CONSTRAINT release_execution_parameters_release_execution_id_fkey FOREIGN KEY(release_execution_id) REFERENCES release_executions (id) ON DELETE CASCADE
);

CREATE TABLE ticket_approvals (
	id SERIAL NOT NULL, 
	ticket_id INTEGER NOT NULL, 
	requested_by INTEGER, 
	reviewed_by INTEGER, 
	status VARCHAR(20) NOT NULL, 
	note TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	reviewed_at TIMESTAMP WITHOUT TIME ZONE, 
	CONSTRAINT ticket_approvals_pkey PRIMARY KEY (id), 
	CONSTRAINT ticket_approvals_requested_by_fkey FOREIGN KEY(requested_by) REFERENCES users (id) ON DELETE SET NULL, 
	CONSTRAINT ticket_approvals_reviewed_by_fkey FOREIGN KEY(reviewed_by) REFERENCES users (id) ON DELETE SET NULL, 
	CONSTRAINT ticket_approvals_ticket_id_fkey FOREIGN KEY(ticket_id) REFERENCES tickets (id) ON DELETE CASCADE, 
	CONSTRAINT check_approval_status CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[]))
);

CREATE TABLE ticket_attachments (
	id SERIAL NOT NULL, 
	ticket_id INTEGER NOT NULL, 
	original_filename VARCHAR(255) NOT NULL, 
	stored_filename VARCHAR(255) NOT NULL, 
	file_size INTEGER, 
	mime_type VARCHAR(100), 
	uploaded_by INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT ticket_attachments_pkey PRIMARY KEY (id), 
	CONSTRAINT ticket_attachments_ticket_id_fkey FOREIGN KEY(ticket_id) REFERENCES tickets (id) ON DELETE CASCADE, 
	CONSTRAINT ticket_attachments_uploaded_by_fkey FOREIGN KEY(uploaded_by) REFERENCES users (id) ON DELETE SET NULL, 
	CONSTRAINT ticket_attachments_stored_filename_key UNIQUE (stored_filename)
);

CREATE TABLE ticket_comments (
	id SERIAL NOT NULL, 
	ticket_id INTEGER NOT NULL, 
	body TEXT NOT NULL, 
	created_by INTEGER, 
	edited_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT ticket_comments_pkey PRIMARY KEY (id), 
	CONSTRAINT ticket_comments_created_by_fkey FOREIGN KEY(created_by) REFERENCES users (id) ON DELETE SET NULL, 
	CONSTRAINT ticket_comments_ticket_id_fkey FOREIGN KEY(ticket_id) REFERENCES tickets (id) ON DELETE CASCADE
);

CREATE TABLE ticket_history (
	id SERIAL NOT NULL, 
	ticket_id INTEGER NOT NULL, 
	changed_by INTEGER, 
	field_name VARCHAR(100) NOT NULL, 
	old_value TEXT, 
	new_value TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT ticket_history_pkey PRIMARY KEY (id), 
	CONSTRAINT ticket_history_changed_by_fkey FOREIGN KEY(changed_by) REFERENCES users (id) ON DELETE SET NULL, 
	CONSTRAINT ticket_history_ticket_id_fkey FOREIGN KEY(ticket_id) REFERENCES tickets (id) ON DELETE CASCADE
);

CREATE TABLE artifacts (
	id SERIAL NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	version VARCHAR(100) NOT NULL, 
	artifact_type VARCHAR(50) DEFAULT 'build'::character varying, 
	pipeline_execution_id INTEGER, 
	release_execution_id INTEGER, 
	storage_path TEXT, 
	download_url TEXT, 
	size_bytes BIGINT, 
	checksum VARCHAR(255), 
	artifact_metadata JSONB, 
	created_by VARCHAR(255), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT artifacts_pkey PRIMARY KEY (id), 
	CONSTRAINT artifacts_pipeline_execution_id_fkey FOREIGN KEY(pipeline_execution_id) REFERENCES pipeline_executions (id) ON DELETE CASCADE, 
	CONSTRAINT artifacts_release_execution_id_fkey FOREIGN KEY(release_execution_id) REFERENCES release_executions (id) ON DELETE CASCADE, 
	CONSTRAINT check_artifact_type CHECK (artifact_type::text = ANY (ARRAY['build'::character varying::text, 'container'::character varying::text, 'package'::character varying::text, 'file'::character varying::text, 'other'::character varying::text]))
);

CREATE TABLE pipeline_execution_logs (
	id SERIAL NOT NULL, 
	pipeline_execution_id INTEGER NOT NULL, 
	log_level VARCHAR(20) DEFAULT 'info'::character varying, 
	message TEXT NOT NULL, 
	timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	step_name VARCHAR(255), 
	step_index INTEGER, 
	source VARCHAR(50) DEFAULT 'system'::character varying, 
	CONSTRAINT pipeline_execution_logs_pkey PRIMARY KEY (id), 
	CONSTRAINT pipeline_execution_logs_pipeline_execution_id_fkey FOREIGN KEY(pipeline_execution_id) REFERENCES pipeline_executions (id) ON DELETE CASCADE, 
	CONSTRAINT pipeline_execution_logs_log_level_check CHECK (log_level::text = ANY (ARRAY['debug'::character varying::text, 'info'::character varying::text, 'warning'::character varying::text, 'error'::character varying::text, 'success'::character varying::text])), 
	CONSTRAINT pipeline_execution_logs_source_check CHECK (source::text = ANY (ARRAY['system'::character varying::text, 'agent'::character varying::text, 'user'::character varying::text]))
);

CREATE TABLE pipeline_execution_params (
	id SERIAL NOT NULL, 
	execution_id INTEGER NOT NULL, 
	param_name VARCHAR(255) NOT NULL, 
	param_value TEXT NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	CONSTRAINT pipeline_execution_params_pkey PRIMARY KEY (id), 
	CONSTRAINT pipeline_execution_params_execution_id_fkey FOREIGN KEY(execution_id) REFERENCES pipeline_executions (id) ON DELETE CASCADE
);

CREATE TABLE pipeline_pickup (
	id SERIAL NOT NULL, 
	pipeline_execution_id INTEGER NOT NULL, 
	pipeline_id INTEGER NOT NULL, 
	pipeline_name VARCHAR(255), 
	agent_id INTEGER NOT NULL, 
	agent_uuid VARCHAR(255) NOT NULL, 
	agent_name VARCHAR(255), 
	status VARCHAR(50) DEFAULT 'pending'::character varying, 
	priority INTEGER DEFAULT 0, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	picked_up_at TIMESTAMP WITHOUT TIME ZONE, 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	error_message TEXT, 
	retry_count INTEGER DEFAULT 0, 
	max_retries INTEGER DEFAULT 3, 
	CONSTRAINT pipeline_pickup_pkey PRIMARY KEY (id), 
	CONSTRAINT fk_pipeline_pickup_agent FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
	CONSTRAINT fk_pipeline_pickup_execution FOREIGN KEY(pipeline_execution_id) REFERENCES pipeline_executions (id) ON DELETE CASCADE, 
	CONSTRAINT fk_pipeline_pickup_pipeline FOREIGN KEY(pipeline_id) REFERENCES pipelines (id) ON DELETE CASCADE, 
	CONSTRAINT check_pipeline_pickup_status CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'picked_up'::character varying::text, 'in_progress'::character varying::text, 'completed'::character varying::text, 'failed'::character varying::text, 'cancelled'::character varying::text]))
);

CREATE TABLE stage_executions (
	id SERIAL NOT NULL, 
	release_execution_id INTEGER, 
	release_stage_id INTEGER, 
	environment_id INTEGER, 
	environment_name VARCHAR(100), 
	status VARCHAR(50) DEFAULT 'pending'::character varying, 
	pipeline_execution_id INTEGER, 
	approval_status VARCHAR(50) DEFAULT 'not_required'::character varying, 
	approved_by VARCHAR(255), 
	approved_at TIMESTAMP WITHOUT TIME ZONE, 
	approval_comments TEXT, 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	duration_seconds INTEGER, 
	error_message TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	agent_id INTEGER, 
	agent_name VARCHAR(255), 
	CONSTRAINT stage_executions_pkey PRIMARY KEY (id), 
	CONSTRAINT stage_executions_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE SET NULL, 
	CONSTRAINT stage_executions_environment_id_fkey FOREIGN KEY(environment_id) REFERENCES environments (id) ON DELETE CASCADE, 
	CONSTRAINT stage_executions_pipeline_execution_id_fkey FOREIGN KEY(pipeline_execution_id) REFERENCES pipeline_executions (id) ON DELETE SET NULL, 
	CONSTRAINT stage_executions_release_execution_id_fkey FOREIGN KEY(release_execution_id) REFERENCES release_executions (id) ON DELETE CASCADE, 
	CONSTRAINT stage_executions_release_stage_id_fkey FOREIGN KEY(release_stage_id) REFERENCES release_stages (id) ON DELETE CASCADE, 
	CONSTRAINT check_approval_status CHECK (approval_status::text = ANY (ARRAY['not_required'::character varying::text, 'pending'::character varying::text, 'approved'::character varying::text, 'rejected'::character varying::text])), 
	CONSTRAINT check_stage_execution_status CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'awaiting_approval'::character varying::text, 'in_progress'::character varying::text, 'succeeded'::character varying::text, 'failed'::character varying::text, 'cancelled'::character varying::text, 'skipped'::character varying::text]))
);

CREATE TABLE release_pickup (
	id SERIAL NOT NULL, 
	release_execution_id INTEGER NOT NULL, 
	stage_execution_id INTEGER NOT NULL, 
	agent_id INTEGER NOT NULL, 
	agent_uuid VARCHAR(255) NOT NULL, 
	agent_name VARCHAR(255), 
	status VARCHAR(50) DEFAULT 'pending'::character varying, 
	priority INTEGER DEFAULT 0, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	picked_up_at TIMESTAMP WITHOUT TIME ZONE, 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	error_message TEXT, 
	retry_count INTEGER DEFAULT 0, 
	max_retries INTEGER DEFAULT 3, 
	CONSTRAINT release_pickup_pkey PRIMARY KEY (id), 
	CONSTRAINT release_pickup_agent_id_fkey FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
	CONSTRAINT release_pickup_release_execution_id_fkey FOREIGN KEY(release_execution_id) REFERENCES release_executions (id) ON DELETE CASCADE, 
	CONSTRAINT release_pickup_stage_execution_id_fkey FOREIGN KEY(stage_execution_id) REFERENCES stage_executions (id) ON DELETE CASCADE, 
	CONSTRAINT release_pickup_status_check CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'picked_up'::character varying::text, 'in_progress'::character varying::text, 'completed'::character varying::text, 'failed'::character varying::text, 'cancelled'::character varying::text]))
);

CREATE TABLE stage_execution_logs (
	id SERIAL NOT NULL, 
	stage_execution_id INTEGER NOT NULL, 
	log_level VARCHAR(20) DEFAULT 'info'::character varying, 
	message TEXT NOT NULL, 
	timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	task_name VARCHAR(255), 
	source VARCHAR(50) DEFAULT 'system'::character varying, 
	CONSTRAINT stage_execution_logs_pkey PRIMARY KEY (id), 
	CONSTRAINT stage_execution_logs_stage_execution_id_fkey FOREIGN KEY(stage_execution_id) REFERENCES stage_executions (id) ON DELETE CASCADE, 
	CONSTRAINT stage_execution_logs_log_level_check CHECK (log_level::text = ANY (ARRAY['debug'::character varying::text, 'info'::character varying::text, 'warning'::character varying::text, 'error'::character varying::text, 'success'::character varying::text])), 
	CONSTRAINT stage_execution_logs_source_check CHECK (source::text = ANY (ARRAY['system'::character varying::text, 'agent'::character varying::text, 'user'::character varying::text]))
);

-- ============================================================
-- Indexes (beyond inline PK/UNIQUE already in CREATE TABLE)
-- ============================================================
CREATE INDEX ix_alert_settings_id ON alert_settings (id);
CREATE INDEX idx_email_log_created ON email_log (created_at);
CREATE UNIQUE INDEX uq_email_log_idem ON email_log (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX ix_roles_id ON roles (id);
CREATE UNIQUE INDEX ix_roles_name ON roles (name);
CREATE INDEX ix_rollback_scripts_id ON rollback_scripts (id);
CREATE INDEX idx_statistics_date ON statistics (stat_date DESC);
CREATE UNIQUE INDEX ix_system_modules_key ON system_modules (key);
CREATE INDEX ix_system_modules_id ON system_modules (id);
CREATE INDEX idx_transfer_files_created ON transfer_files (created_at DESC);
CREATE INDEX idx_transfer_files_type ON transfer_files (file_type);
CREATE INDEX idx_transfer_files_version ON transfer_files (version);
CREATE UNIQUE INDEX ix_users_username ON users (username);
CREATE UNIQUE INDEX ix_users_email ON users (email);
CREATE INDEX ix_users_id ON users (id);
CREATE INDEX ix_audit_logs_id ON audit_logs (id);
CREATE INDEX ix_audit_logs_resource_type ON audit_logs (resource_type);
CREATE INDEX ix_audit_logs_action ON audit_logs (action);
CREATE INDEX ix_audit_logs_created_at ON audit_logs (created_at);
CREATE UNIQUE INDEX ix_customers_name ON customers (name);
CREATE INDEX ix_customers_id ON customers (id);
CREATE INDEX idx_customers_name ON customers (name);
CREATE INDEX idx_customers_is_active ON customers (is_active);
CREATE INDEX idx_prt_token_hash ON password_reset_tokens (token_hash);
CREATE INDEX idx_prt_user_id ON password_reset_tokens (user_id);
CREATE INDEX ix_rollback_database_objects_script_id ON rollback_database_objects (script_id);
CREATE INDEX ix_rollback_database_objects_id ON rollback_database_objects (id);
CREATE INDEX ix_rollback_database_objects_object_name ON rollback_database_objects (object_name);
CREATE INDEX ix_rollback_database_objects_object_type ON rollback_database_objects (object_type);
CREATE INDEX ix_sessions_id ON sessions (id);
CREATE UNIQUE INDEX ix_sessions_session_token ON sessions (session_token);
CREATE INDEX idx_pickup_status ON transfer_file_pickup (status);
CREATE INDEX idx_pickup_requested ON transfer_file_pickup (requested_at DESC);
CREATE INDEX idx_pickup_agent_uuid ON transfer_file_pickup (agent_uuid);
CREATE INDEX ix_user_roles_id ON user_roles (id);
CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);
CREATE INDEX idx_user_roles_user_id ON user_roles (user_id);
CREATE INDEX idx_user_sessions_token_hash ON user_sessions (token_hash);
CREATE INDEX idx_user_sessions_user_id ON user_sessions (user_id);
CREATE INDEX idx_variables_environment_id ON variables (environment_id);
CREATE INDEX idx_variables_variable_group_id ON variables (variable_group_id);
CREATE INDEX idx_agents_parent_agent_id ON agents (parent_agent_id);
CREATE INDEX idx_agents_location ON agents (location);
CREATE INDEX idx_agents_status ON agents (status);
CREATE INDEX idx_agents_customer_id ON agents (customer_id);
CREATE INDEX idx_agents_last_seen ON agents (last_seen);
CREATE INDEX ix_ai_settings_id ON ai_settings (id);
CREATE INDEX ix_ai_settings_customer_id ON ai_settings (customer_id);
CREATE INDEX ix_email_alerts_received_at ON email_alerts (received_at);
CREATE INDEX ix_email_alerts_id ON email_alerts (id);
CREATE INDEX ix_email_alerts_customer_id ON email_alerts (customer_id);
CREATE INDEX ix_email_alerts_category ON email_alerts (category);
CREATE INDEX ix_email_configs_id ON email_configs (id);
CREATE INDEX ix_email_configs_customer_id ON email_configs (customer_id);
CREATE INDEX idx_services_customer_id ON services (customer_id);
CREATE INDEX idx_services_status ON services (status);
CREATE INDEX idx_services_last_check ON services (last_check DESC);
CREATE INDEX idx_services_type ON services (type);
CREATE INDEX idx_services_category ON services (category);
CREATE INDEX idx_user_customers_customer_id ON user_customers (customer_id);
CREATE INDEX idx_user_customers_is_default ON user_customers (user_id, is_default);
CREATE INDEX idx_user_customers_user_id ON user_customers (user_id);
CREATE INDEX ix_user_customers_id ON user_customers (id);
CREATE INDEX idx_agent_commands_agent_id ON agent_commands (agent_id);
CREATE INDEX idx_agent_commands_status ON agent_commands (status);
CREATE INDEX ix_agent_commands_agent_id ON agent_commands (agent_id);
CREATE INDEX ix_agent_commands_id ON agent_commands (id);
CREATE INDEX ix_agent_drive_info_id ON agent_drive_info (id);
CREATE INDEX idx_agent_logs_level ON agent_logs (level);
CREATE INDEX idx_agent_logs_agent_id ON agent_logs (agent_id);
CREATE INDEX idx_agent_logs_timestamp ON agent_logs (timestamp DESC);
CREATE INDEX idx_agent_resource_agent_id ON agent_resource_data (agent_id);
CREATE INDEX idx_agent_resource_timestamp ON agent_resource_data (timestamp DESC);
CREATE INDEX ix_agent_website_pings_id ON agent_website_pings (id);
CREATE INDEX ix_agent_windows_services_id ON agent_windows_services (id);
CREATE INDEX idx_pipelines_customer_id ON pipelines (customer_id);
CREATE INDEX idx_pipelines_status ON pipelines (status);
CREATE INDEX idx_pipelines_last_run ON pipelines (last_run DESC);
CREATE INDEX idx_pipelines_branch ON pipelines (branch);
CREATE INDEX idx_service_health_timestamp ON service_health_history (timestamp DESC);
CREATE INDEX idx_service_health_service_id ON service_health_history (service_id);
CREATE INDEX idx_pipeline_params_pipeline_id ON pipeline_parameters (pipeline_id);
CREATE INDEX idx_pipeline_steps_pipeline_id ON pipeline_steps (pipeline_id);
CREATE INDEX idx_pipeline_steps_order ON pipeline_steps (pipeline_id, step_order);
CREATE INDEX idx_releases_pipeline_id ON releases (pipeline_id);
CREATE INDEX idx_releases_customer_id ON releases (customer_id);
CREATE INDEX idx_releases_status ON releases (status);
CREATE INDEX idx_tasks_start_time ON tasks (start_time DESC);
CREATE INDEX idx_tasks_status ON tasks (status);
CREATE INDEX idx_tasks_pipeline_id ON tasks (pipeline_id);
CREATE INDEX idx_tasks_agent_id ON tasks (agent_id);
CREATE INDEX idx_release_executions_status ON release_executions (status);
CREATE INDEX idx_release_executions_release_id ON release_executions (release_id);
CREATE INDEX ix_release_pipelines_id ON release_pipelines (id);
CREATE INDEX idx_release_stages_release_id ON release_stages (release_id);
CREATE INDEX idx_release_stages_environment_id ON release_stages (environment_id);
CREATE INDEX idx_release_stages_agent_id ON release_stages (agent_id);
CREATE INDEX ix_tickets_customer_id ON tickets (customer_id);
CREATE UNIQUE INDEX ix_tickets_ticket_number ON tickets (ticket_number);
CREATE INDEX ix_tickets_id ON tickets (id);
CREATE INDEX idx_pe_release_execution_id ON pipeline_executions (release_execution_id);
CREATE INDEX idx_pipeline_executions_pipeline_id ON pipeline_executions (pipeline_id);
CREATE INDEX idx_pe_release_pipeline_id ON pipeline_executions (release_pipeline_id);
CREATE INDEX idx_pipeline_executions_status ON pipeline_executions (status);
CREATE INDEX idx_pipeline_executions_started_at ON pipeline_executions (started_at DESC);
CREATE INDEX idx_pipeline_executions_agent_id ON pipeline_executions (agent_id);
CREATE INDEX ix_ticket_approvals_ticket_id ON ticket_approvals (ticket_id);
CREATE INDEX ix_ticket_approvals_id ON ticket_approvals (id);
CREATE INDEX ix_ticket_attachments_id ON ticket_attachments (id);
CREATE INDEX ix_ticket_attachments_ticket_id ON ticket_attachments (ticket_id);
CREATE INDEX ix_ticket_comments_ticket_id ON ticket_comments (ticket_id);
CREATE INDEX ix_ticket_comments_id ON ticket_comments (id);
CREATE INDEX ix_ticket_history_id ON ticket_history (id);
CREATE INDEX ix_ticket_history_ticket_id ON ticket_history (ticket_id);
CREATE INDEX idx_artifacts_pipeline_execution_id ON artifacts (pipeline_execution_id);
CREATE INDEX idx_artifacts_release_execution_id ON artifacts (release_execution_id);
CREATE INDEX idx_pipeline_execution_logs_execution_id ON pipeline_execution_logs (pipeline_execution_id);
CREATE INDEX idx_pipeline_execution_logs_timestamp ON pipeline_execution_logs (timestamp DESC);
CREATE INDEX idx_pipeline_execution_logs_level ON pipeline_execution_logs (log_level);
CREATE INDEX idx_execution_params_execution_id ON pipeline_execution_params (execution_id);
CREATE INDEX idx_pipeline_pickup_execution ON pipeline_pickup (pipeline_execution_id);
CREATE INDEX idx_pipeline_pickup_status ON pipeline_pickup (status);
CREATE INDEX idx_pipeline_pickup_created_at ON pipeline_pickup (created_at);
CREATE INDEX idx_pipeline_pickup_agent_uuid ON pipeline_pickup (agent_uuid);
CREATE INDEX idx_stage_executions_agent_id ON stage_executions (agent_id);
CREATE INDEX idx_stage_executions_release_execution_id ON stage_executions (release_execution_id);
CREATE INDEX idx_stage_executions_environment_id ON stage_executions (environment_id);
CREATE INDEX idx_release_pickup_created_at ON release_pickup (created_at DESC);
CREATE INDEX idx_release_pickup_status ON release_pickup (status);
CREATE INDEX idx_release_pickup_agent_status ON release_pickup (agent_uuid, status);
CREATE INDEX idx_release_pickup_agent_uuid ON release_pickup (agent_uuid);
CREATE INDEX idx_stage_execution_logs_timestamp ON stage_execution_logs (timestamp DESC);
CREATE INDEX idx_stage_execution_logs_execution_id ON stage_execution_logs (stage_execution_id);
CREATE INDEX idx_stage_execution_logs_level ON stage_execution_logs (log_level);

-- ============================================================
-- Views
-- ============================================================
CREATE OR REPLACE VIEW dashboard_pipelines AS
SELECT id,
    name,
    status,
    relative_time(last_run) AS last_run,
    duration,
    branch,
    commit
   FROM pipelines
  ORDER BY (relative_time(last_run)) DESC;

CREATE OR REPLACE VIEW customer_statistics AS
SELECT c.id AS customer_id,
    c.name AS customer_name,
    c.display_name,
    c.is_active,
    count(DISTINCT a.id) AS total_agents,
    count(DISTINCT
        CASE
            WHEN a.status::text = 'online'::text THEN a.id
            ELSE NULL::integer
        END) AS online_agents,
    count(DISTINCT p.id) AS total_pipelines,
    count(DISTINCT
        CASE
            WHEN p.status::text = 'success'::text THEN p.id
            ELSE NULL::integer
        END) AS successful_pipelines,
    count(DISTINCT r.id) AS total_releases,
    count(DISTINCT s.id) AS total_services,
    count(DISTINCT uc.user_id) AS total_users
   FROM customers c
     LEFT JOIN agents a ON c.id = a.customer_id
     LEFT JOIN pipelines p ON c.id = p.customer_id
     LEFT JOIN releases r ON c.id = r.customer_id
     LEFT JOIN services s ON c.id = s.customer_id
     LEFT JOIN user_customers uc ON c.id = uc.customer_id
  GROUP BY c.id, c.name, c.display_name, c.is_active;

CREATE OR REPLACE VIEW dashboard_agents AS
SELECT id,
    name,
    status,
    relative_time(last_seen) AS last_seen,
    jobs,
    location,
    cpu,
    memory,
    uuid
   FROM agents
  ORDER BY (relative_time(last_seen)) DESC;

CREATE OR REPLACE VIEW dashboard_tasks AS
SELECT id,
    name,
    COALESCE(pipeline_name, ( SELECT pipelines.name
           FROM pipelines
          WHERE pipelines.id = tasks.pipeline_id)) AS pipeline,
    COALESCE(agent_name, ( SELECT agents.name
           FROM agents
          WHERE agents.id = tasks.agent_id)) AS agent,
    status,
    to_char(start_time, 'HH:MI AM'::text) AS start_time,
    COALESCE(duration, '-'::character varying) AS duration
   FROM tasks
  ORDER BY created_at DESC;

-- ============================================================
-- Functions
-- ============================================================
CREATE OR REPLACE FUNCTION public.calculate_duration(start_time timestamp without time zone, end_time timestamp without time zone)
 RETURNS character varying
 LANGUAGE plpgsql
AS $function$
DECLARE
    duration_seconds INTEGER;
    minutes INTEGER;
    seconds INTEGER;
BEGIN
    IF start_time IS NULL OR end_time IS NULL THEN
        RETURN '-';
    END IF;
    
    duration_seconds := EXTRACT(EPOCH FROM (end_time - start_time))::INTEGER;
    minutes := duration_seconds / 60;
    seconds := duration_seconds % 60;
    
    RETURN minutes || 'm ' || seconds || 's';
END;
$function$;

CREATE OR REPLACE FUNCTION public.relative_time(timestamp_value timestamp without time zone)
 RETURNS character varying
 LANGUAGE plpgsql
AS $function$
DECLARE
    seconds_diff INTEGER;
    minutes_diff INTEGER;
    hours_diff INTEGER;
    days_diff INTEGER;
BEGIN
    IF timestamp_value IS NULL THEN
        RETURN 'never';
    END IF;
    
    seconds_diff := EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - timestamp_value))::INTEGER;
    
    IF seconds_diff < 60 THEN
        RETURN 'just now';
    ELSIF seconds_diff < 3600 THEN
        minutes_diff := seconds_diff / 60;
        RETURN minutes_diff || ' minute' || (CASE WHEN minutes_diff > 1 THEN 's' ELSE '' END) || ' ago';
    ELSIF seconds_diff < 86400 THEN
        hours_diff := seconds_diff / 3600;
        RETURN hours_diff || ' hour' || (CASE WHEN hours_diff > 1 THEN 's' ELSE '' END) || ' ago';
    ELSE
        days_diff := seconds_diff / 86400;
        RETURN days_diff || ' day' || (CASE WHEN days_diff > 1 THEN 's' ELSE '' END) || ' ago';
    END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$;

-- ============================================================
-- Triggers
-- ============================================================
CREATE TRIGGER update_agents_updated_at BEFORE UPDATE ON public.agents FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_customers_updated_at BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_pipeline_params_updated_at BEFORE UPDATE ON public.pipeline_parameters FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_pipeline_steps_updated_at BEFORE UPDATE ON public.pipeline_steps FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_pipelines_updated_at BEFORE UPDATE ON public.pipelines FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_services_updated_at BEFORE UPDATE ON public.services FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
"""


def upgrade() -> None:
    # Single multi-statement execution (not split on ';') because the function
    # bodies below are $function$...$function$-quoted and contain their own
    # internal semicolons. op.execute() with a plain string bypasses
    # SQLAlchemy's text() bind-parameter parsing, which would otherwise choke
    # on the literal '::' Postgres cast syntax used throughout.
    op.execute(_BASELINE_DDL)


def downgrade() -> None:
    raise NotImplementedError(
        "This is the baseline revision (captured from a live database, not "
        "authored by hand) — downgrading past it is not supported."
    )
